
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS myPodDB;
 use myPodDB;

CREATE TABLE IF NOT EXISTS registre (
  id INT(11) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  adressemail VARCHAR(100) NOT NULL,
  motdepasse VARCHAR(100) NOT NULL,
  pseudo VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);


ALTER TABLE `registre`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `registre`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;


INSERT INTO registre (nom, prenom, adressemail, motdepasse, pseudo) VALUES ('dine', 'dine', 'dine@dine.com', 'dine', 'dine');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
